### ISSUE TITLE
vmware_fusion templates not installed on 'vagrant plugin install oscar'

### ISSUE THREAD

**Issue by unclespeedo** [adrienthebo/oscar#40]
I was able to reproduce this on two separate OS X hosts (10.10.2)

After running 'vagrant plugin install oscar' successfully, I run 'vagrant oscar init' and get 

> fileutils.rb:1375:in `copy': unknown file type: ~/.vagrant.d/gems/gems/oscar-0.4.1/templates/oscar-init-skeleton/vmware_fusion/. (RuntimeError)

Upon inspecting ~/.vagrant.d/gems/gems/oscar-0.4.1/templates/oscar-init-skeleton/ the vmware_fusion directory does not exist.

I'm able to get around this issue by pulling the vmware_fusion templates from github and manually placing them in the correct location.

 INFO global: Vagrant version: 1.7.2
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant"
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Darwin"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_NO_PLUGINS="1"
 INFO global: VAGRANT_VAGRANTFILE="plugin_command_1423846951"
 INFO global: Plugins:
 INFO global:   - bundler = 1.7.11
 INFO global:   - json = 1.8.2
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rdoc = 4.2.0
 INFO global:   - rest-client = 1.6.8
 INFO global:   - vagrant-share = 1.1.3
 INFO global:   - vagrant-vmware-fusion = 3.2.1

**Comment by adamcrews** [comment]
@adrienthebo Any chance of getting an updated Gem published that has these templates?

**Comment by adrienthebo** [comment]
@adamcrews I don't have the time to do a lot of investigation into this but I could push a new gem, would you be able to poke around and see what's going on?

**Comment by adamcrews** [comment]
@adrienthebo This was fixed with https://github.com/adrienthebo/oscar/pull/29 but a new gem was not released.   Without a new gem the workaround is to just drop the template files in the proper place as noted above.

**Comment by adrienthebo** [comment]
Oh. That'd do it.

**Comment by adrienthebo** [comment]
Released in 0.4.2: https://rubygems.org/gems/oscar/versions/0.4.2
